name = "first-worker"
type = "javascript"

account_id = ""
route = "dev.example.com/*"

[env.staging]
name = "my-worker-staging"
vars = { ENVIRONMENT = "staging" }
route = "staging.example.com/*"


[env.production]
name = "my-worker"
vars = { ENVIRONMENT = "production" }
route = "example.com/*"

