name = "first-worker"
type = "javascript"
compatibility_date = "2021-09-20"
account_id = ""

[env.staging]
name = "my-worker-staging"
vars = { ENVIRONMENT = "staging" }

[env.production]
name = "my-worker"
vars = { ENVIRONMENT = "production" }