name: PROD-Deploy
on:
  push:
    branches:
      - master
jobs:
  setup:
    runs-on: ubuntu-latest
    name: Clean Install
    steps:
      - run: npm ci
  build:
    needs: setup
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: 'npm run build'

  publish:
    needs: build
    name: Publish
    runs-on: ubuntu-latest
    steps:
      uses: cloudflare/wrangler-action@1.3.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
