name: PROD-Deploy
on:
  push:
    branches:
      - master
jobs:
  pre-setup:
    runs-on: ubuntu-latest
    name: Pre Setup
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
  setup:
    needs: pre-setup
    runs-on: ubuntu-latest
    name: Clean Install
    steps:
      - run: npm ci
  build:
    needs: setup
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: 'npm run build'

  publish:
    needs: build
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
