name: PROD-Deploy
on:
  push:
    branches:
      - master
jobs:
  setup:
    runs-on: ubuntu-latest
    name: Clean Install
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
  build:
    needs: setup
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: npm run build --if-present
  test:
    needs: setup
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: npm run test --if-present
  publish:
    needs: build
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
